language: python
python:
  - "3.5"
  - "3.6"
env:
  - TRAVIS_NODE_VERSION="8"
  - TRAVIS_NODE_VERSION="9"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - cd minos/server && npm install && cd ../..
  - pip3 install -e . -r requirements.txt
